In [20]:
# importando a numpy 
import numpy as np 

def pl():
    print('------------------------------')

In [5]:
# criando uma matriz unidimensional ( vetor )
matriz = np.array([12,23,1,5,543,10])
print(matriz)
print(type(matriz))

[ 12  23   1   5 543  10]
<class 'numpy.ndarray'>


In [8]:
# criar o array com um tipo específico 
# cria o array como float de 64bits

mt_float = np.array([1,2,3], dtype = np.float64)
print(mt_float)
print(type(mt_float))
mt_int = np.array([1,2,3], dtype = np.int32)
print(mt_int)
print(type(mt_int))

[1. 2. 3.]
<class 'numpy.ndarray'>
[1 2 3]
<class 'numpy.ndarray'>


In [10]:
# mudando o tipo do array

mt_new = np.array([1.4,5.2,8.8])
print(mt_new)

# quando fazemos uma transformação de float -> int, os valores são truncados
mt_new_int = mt_new.astype(np.int32)
print(mt_new_int)

[1.4 5.2 8.8]
[1 5 8]


In [12]:
# transoformando de int -> float

mt5 = np.array([1,2,3,4])
print(mt5)
mt6 = mt5.astype(float)
print(mt6)

[1 2 3 4]
[1. 2. 3. 4.]


In [14]:
# criando matrizes com mais de uma dimensão 

mt7 = np.array([[7,2,4], [4,4,4],[9,12,5]])
print(mt7)

[[ 7  2  4]
 [ 4  4  4]
 [ 9 12  5]]


In [23]:
# podemos criar arrays tipificados 
# empty -> não são inicializados, é != de vazio

# criando apenas o espaço na memoria da matriz que pode ser escolhida, mas apenas não é inicializado os valores que ocuparão cada espaço da matriz
vazio = np.empty([3,2], dtype = int)
print(vazio)

pl()

# criando matriz 4x3 com valores zero
zeros = np.zeros([4,3])
print(zeros)

pl()

#com valoes iguais a um 
um = np.ones([5,7])
print(um)

pl()

# cria matriz quadrada com diagonal principal com valores 1 e os outros valores zero 
diagonal = np.eye(5)
print(diagonal)

[[ 1717986918  1073112678]
 [ -858993459  1075104972]
 [-1717986918  1075943833]]
------------------------------
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
------------------------------
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
------------------------------
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [31]:
# criando valores aleatorios 

numero_ale = np.random.random((5))
print(numero_ale)

pl()

# valores aleatorios, distribuicao normal contendo negativos 
numero_ale2 = np.random.randn((5))
print(numero_ale2)

pl()

#valores aletorios 3x4
ale3 = (100*np.random.random((3,4)))
print(ale3)

[0.9402091  0.83029916 0.4843653  0.83140715 0.24008919]
------------------------------
[-0.11353357 -1.93259307  1.04823365  0.34786272 -1.08908265]
------------------------------
[[28.34480787 38.3277225  92.26637433 72.05673178]
 [36.67864376 74.71811144 55.58393427 29.49892863]
 [54.71872663 41.90955143 45.07040435 64.36597644]]


In [42]:
# outra forma de gerar valores aleatorios

#uso de semente
gnr = np.random.default_rng(10)
ale5 = gnr.random(3)
print(ale5)

# gerar inteiros em matriz 3x4
ale6 = gnr.integers(10, size=(3,4))
print(ale6)

[0.95600171 0.20768181 0.82844489]
[[5 1 8 5]
 [1 1 4 6]
 [4 8 0 4]]


In [43]:
# removendo repetições

j = np.array([1,2,3,4,5,6,7,7,7,23,5,5,23,1,2])
j = np.unique(j)
print(j)

[ 1  2  3  4  5  6  7 23]


In [47]:
# funções especificas

#cria a matriz bidimensional k 
k = np.array([[17,22,43],[27,25,14],[15,24,32]])
print(k)

pl()

#mostra um elemento especifico 
print(k[0][2])

pl()

#mostra o tamanho das dimensões da matriz k 
print(k.shape)

[[17 22 43]
 [27 25 14]
 [15 24 32]]
------------------------------
43
------------------------------
(3, 3)


In [49]:
# funcoes matematicas

# mostra valor maximo da matriz k 
print(k.max())

#mostra valor minimo da matriz k 
print(k.min())


# !-----AULA CONTINUA COM A EXPLICAÇÃO DE UM MONTE DE FUNÇÕES MATEMÁTICAS------! 

43
14
